### ISSUE TITLE
[cli] distance cmd

### ISSUE THREAD

**Issue by davidcawork** [intrig-unicamp/mininet-wifi#577]
Hello @ramonfontes,

I was checking the CLI of Mininet-WiFi, in particular, the `distance` cmd. I got this error because the attribute position is not defined in the `sta1` and `sta2`. 

### Error:

```bash
user@sdn-wifi:~$ sudo mn --wifi
*** Adding stations:
sta1 sta2 
*** Adding access points:
ap1 
*** Configuring nodes...
*** Creating network
*** Adding controller
*** Adding hosts:

*** Adding switches:

*** Adding links:
(sta1, ap1) (sta2, ap1) 
*** Starting controller(s)
c0 
*** Starting L2 nodes
ap1 ...
*** Starting CLI:
mininet-wifi> distance sta1 sta2
--------------------------------------------------------------------------------
Caught exception. Cleaning up...

AttributeError: 'Station' object has no attribute 'position'
--------------------------------------------------------------------------------
```

### Mininet-WiFi version

Right now, I'm working with a Ubuntu 22.04 and this Mininet-WiFi version:

```bash
user@sdn-wifi:~$ sudo mn --version
2.6
```

### Possible solution 😄 

Maybe, we can check first if the attribute `position` already exists, in function [`def get_distance_to`](https://github.com/intrig-unicamp/mininet-wifi/blob/master/mn_wifi/node.py#L289C5-L289C24). Something like this:

```python
def get_distance_to(self, dst):
    """Get the distance between two nodes
    :param self: source node
    :param dst: destination node"""
    pos_src = self.position
    pos_dst = dst.position

    if hasattr(self, 'position') and hasattr(dst, 'position'):
        x = (float(pos_src[0]) - float(pos_dst[0])) ** 2
        y = (float(pos_src[1]) - float(pos_dst[1])) ** 2
        z = (float(pos_src[2]) - float(pos_dst[2])) ** 2
        dist = math.sqrt(x + y + z)
    else:
        dist = 0.0
    return round(dist, 2)
```

If the `position` attribute does not exit, can we return 0? I don't know... What do you think?

Thanks a lot 😄!

**Comment by ramonfontes** [comment]
> I was checking the CLI of Mininet-WiFi, in particular, the distance cmd. I got this error because the attribute position is not defined in the sta1 and sta2.

Yes, that’s an expected error since the nodes have no assigned positions.

> If the position attribute does not exit, can we return 0? I don't know... What do you think?

I’d suggest returning a message like: "No position defined for the nodes." Instead of returning 0, which might be misleading.

Can you send a PR?

**Comment by davidcawork** [comment]
Hi @ramonfontes ! 

You have the PR #578 . Best! :)

**Comment by ramonfontes** [comment]
Thanks @davidcawork!
